#???
server:
  port: 8080

#?????
spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://47.109.206.82:3306/dreamTeam?&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
      date-format: yyyy-MM-dd
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      database: 0
transaction:
  rollback-on-commit-failure: true
  default-timeout: 30

mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志