#端口号
server:
  port: 8080

#数据库配置
spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://47.109.206.82:3306/dreamTeam
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      database: 0
transaction:
  rollback-on-commit-failure: true
  default-timeout: 30

mybatis:
  mapper-locations: classpath:mapper/*.xml

aliyun:
  sms:
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    sign-name: your-sign-name
    template-code: SMS_XXXXXXXX