#???
server:
  port: 8080

#?????
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/software3?&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      database: 0
transaction:
  rollback-on-commit-failure: true
  default-timeout: 30